
CREATE TABLE public.ASISTENCIA (
                ASIS_MED INTEGER NOT NULL,
                ASISTENCIA VARCHAR(50) NOT NULL,
                CONSTRAINT asistencia_pk PRIMARY KEY (ASIS_MED)
);


CREATE TABLE public.MANERA_MORIR (
                MAN_MUER INTEGER NOT NULL,
                TIPO_MUERTE VARCHAR(50) NOT NULL,
                CONSTRAINT manera_morir_pk PRIMARY KEY (MAN_MUER)
);


CREATE TABLE public.EDAD (
                GRU_ED1 INTEGER NOT NULL,
                NOM_EDAD VARCHAR(50) NOT NULL,
                CONSTRAINT edad_pk PRIMARY KEY (GRU_ED1)
);


CREATE TABLE public.EDUCACION (
                NIVEL_EDU INTEGER NOT NULL,
                NOM_NIVEL VARCHAR NOT NULL,
                CONSTRAINT educacion_pk PRIMARY KEY (NIVEL_EDU)
);


CREATE TABLE public.CULTURA (
                IDPERTET INTEGER NOT NULL,
                NOM_CULTURA VARCHAR(50) NOT NULL,
                CONSTRAINT cultura_pk PRIMARY KEY (IDPERTET)
);


CREATE TABLE public.ESTADO_CIVIL (
                EST_CIVIL INTEGER NOT NULL,
                NOM_ESTADO VARCHAR(50) NOT NULL,
                CONSTRAINT estado_civil_pk PRIMARY KEY (EST_CIVIL)
);


CREATE TABLE public.SEXO (
                SEXO INTEGER NOT NULL,
                NOM_SEXO VARCHAR(50) NOT NULL,
                CONSTRAINT sexo_pk PRIMARY KEY (SEXO)
);


CREATE TABLE public.MES (
                MES INTEGER NOT NULL,
                NOM_MES VARCHAR(50) NOT NULL,
                CONSTRAINT mes_pk PRIMARY KEY (MES)
);


CREATE TABLE public.TIPO (
                TIPO_DEFUN INTEGER NOT NULL,
                NOM_TIPO VARCHAR(50) NOT NULL,
                CONSTRAINT tipo_pk PRIMARY KEY (TIPO_DEFUN)
);


CREATE TABLE public.SITIO (
                SIT_DEFUN INTEGER NOT NULL,
                NOM_SIT VARCHAR(50) NOT NULL,
                CONSTRAINT sitio_pk PRIMARY KEY (SIT_DEFUN)
);


CREATE TABLE public.AREA_DFU (
                A_DEFUN INTEGER NOT NULL,
                NOM_DEFU VARCHAR(50) NOT NULL,
                CONSTRAINT area_dfu_pk PRIMARY KEY (A_DEFUN)
);


CREATE TABLE public.CERTIFICACION (
                IDPROFCER INTEGER NOT NULL,
                PROFESION VARCHAR(50) NOT NULL,
                CONS_EXP INTEGER,
                CONSTRAINT certificacion_pk PRIMARY KEY (IDPROFCER)
);


CREATE SEQUENCE public.persona_id_persona_seq;

CREATE TABLE public.PERSONA (
                ID_Persona INTEGER NOT NULL DEFAULT nextval('public.persona_id_persona_seq'),
                OCUPACION VARCHAR(50) NOT NULL,
                ULTCURFAL INTEGER NOT NULL,
                PESO_NAC INTEGER NOT NULL,
                SEXO INTEGER NOT NULL,
                EST_CIVIL INTEGER NOT NULL,
                IDPERTET INTEGER NOT NULL,
                NIVEL_EDU INTEGER NOT NULL,
                GRU_ED1 INTEGER NOT NULL,
                CONSTRAINT persona_pk PRIMARY KEY (ID_Persona)
);


ALTER SEQUENCE public.persona_id_persona_seq OWNED BY public.PERSONA.ID_Persona;

CREATE TABLE public.INSTITUTO (
                COD_INST VARCHAR(50) NOT NULL,
                NOM_INST VARCHAR(50) NOT NULL,
                CONSTRAINT instituto_pk PRIMARY KEY (COD_INST)
);


CREATE TABLE public.DEPERTAMENTO (
                COD_DPTO INTEGER NOT NULL,
                NOM_DEP VARCHAR(50) NOT NULL,
                CONSTRAINT depertamento_pk PRIMARY KEY (COD_DPTO)
);


CREATE TABLE public.DEFUNCION (
                ID_Persona INTEGER NOT NULL,
                ANO INTEGER NOT NULL,
                HORA INTEGER NOT NULL,
                MINUTOS INTEGER NOT NULL,
                MUERTEPORO INTEGER NOT NULL,
                SIMUERTEPO INTEGER,
                C_DIR1 VARCHAR(50),
                C_ANT1 VARCHAR(50),
                CAUSA_666 INTEGER NOT NULL,
                CAU_HOMOL INTEGER NOT NULL,
                TIPO_DEFUN INTEGER NOT NULL,
                MES INTEGER NOT NULL,
                COD_DPTO INTEGER NOT NULL,
                COD_INST VARCHAR(50) NOT NULL,
                A_DEFUN INTEGER NOT NULL,
                SIT_DEFUN INTEGER NOT NULL,
                IDPROFCER INTEGER NOT NULL,
                MAN_MUER INTEGER NOT NULL,
                ASIS_MED INTEGER NOT NULL,
                CONSTRAINT defuncion_pk PRIMARY KEY (ID_Persona)
);


ALTER TABLE public.DEFUNCION ADD CONSTRAINT asistencia_defuncion_fk
FOREIGN KEY (ASIS_MED)
REFERENCES public.ASISTENCIA (ASIS_MED)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT manera_morir_defuncion_fk
FOREIGN KEY (MAN_MUER)
REFERENCES public.MANERA_MORIR (MAN_MUER)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PERSONA ADD CONSTRAINT edad_persona_fk
FOREIGN KEY (GRU_ED1)
REFERENCES public.EDAD (GRU_ED1)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PERSONA ADD CONSTRAINT educacion_persona_fk
FOREIGN KEY (NIVEL_EDU)
REFERENCES public.EDUCACION (NIVEL_EDU)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PERSONA ADD CONSTRAINT cultura_persona_fk
FOREIGN KEY (IDPERTET)
REFERENCES public.CULTURA (IDPERTET)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PERSONA ADD CONSTRAINT estado_civil_persona_fk
FOREIGN KEY (EST_CIVIL)
REFERENCES public.ESTADO_CIVIL (EST_CIVIL)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PERSONA ADD CONSTRAINT sexo_persona_fk
FOREIGN KEY (SEXO)
REFERENCES public.SEXO (SEXO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT mes_defuncion_fk
FOREIGN KEY (MES)
REFERENCES public.MES (MES)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT tipo_defuncion_fk
FOREIGN KEY (TIPO_DEFUN)
REFERENCES public.TIPO (TIPO_DEFUN)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT sitio_defuncion_fk
FOREIGN KEY (SIT_DEFUN)
REFERENCES public.SITIO (SIT_DEFUN)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT area_dfu_defuncion_fk
FOREIGN KEY (A_DEFUN)
REFERENCES public.AREA_DFU (A_DEFUN)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT certificacion_defuncion_fk
FOREIGN KEY (IDPROFCER)
REFERENCES public.CERTIFICACION (IDPROFCER)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT persona_defuncion_fk
FOREIGN KEY (ID_Persona)
REFERENCES public.PERSONA (ID_Persona)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT instituto_defuncion_fk
FOREIGN KEY (COD_INST)
REFERENCES public.INSTITUTO (COD_INST)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.DEFUNCION ADD CONSTRAINT depertamento_defuncion_fk
FOREIGN KEY (COD_DPTO)
REFERENCES public.DEPERTAMENTO (COD_DPTO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
